from subgraphsampling.BasicGraph.GraphModelLib_Simplified_Optimized import graphmodel
from subgraphsampling.BasicGraph.GraphModelLib_Simplified_LSTMTransform_Optimized import graphmodel as graphmodel_large
