#from simplified.BasicGraph.GraphModelLib_Simplified import graphmodel
#from simplified.BasicGraph.GraphModelLib_Simplified_mixedvalidation import graphmodel
from simplified.BasicGraph.GraphModelLib_Simplified_mixedvalidation_otfgraphs import graphmodel

