from simplified.MultistepHierarchicalGraph.GraphModelLib_Simplified_MultistepHierarchical import graphmodel
#from simplified.MultistepHierarchicalGraph.GraphModelLib_Simplified_MultistepHierarchical_lowmem import graphmodel as graphmodel_lowmem
from simplified.MultistepHierarchicalGraph.GraphModelLib_Simplified_MultistepHierarchical_lowmem_mixedvalidation import graphmodel as graphmodel_lowmem
