from BasicGraph.GraphModelLib_v6_Simplified import graphmodel
from BasicGraph.GraphModelLib_v6_Simplified_LSTMTransform import graphmodel as graphmodel_large
from BasicGraph.GraphModelLib_v6_Simplified_Oneshot import graphmodel as graphmodel_multihorizon
from BasicGraph.GraphModelLib_v6_Simplified_LSTMTransform_Oneshot import graphmodel as graphmodel_large_multihorizon