from hierarchical.BasicGraph.GraphModelLib_Simplified_LSTMTransform_Optimized_Constrained import graphmodel
from hierarchical.BasicGraph.GraphModelLib_Simplified_LSTMTransform_Optimized import graphmodel as graphmodel_large
